### ISSUE TITLE
construct_dataset_Market.m

### ISSUE THREAD

**Issue by yangwudi100** [KovenYu/MAR#1]
Hello, i have a question. In matlab code,  file"construct_dataset_Market.m",  line50,51,52,  
"train_labels = uniquize(train_labels);
gallery_labels = uniquize(gallery_labels);
probe_labels = uniquize(probe_labels);"
i do not search any information about function "uniquize" and when i run this matlab file ,something wrong like this "Undefined function 'uniquize' for input arguments of type 'int64'.
Error in construct_dataset_Market (line 50)train_labels = uniquize(train_labels);"
i want to know, why. thanks twice.

**Comment by yangjunting100** [comment]
> Hello, i have a question. In matlab code, file"construct_dataset_Market.m", line50,51,52,
> "train_labels = uniquize(train_labels);
> gallery_labels = uniquize(gallery_labels);
> probe_labels = uniquize(probe_labels);"
> i do not search any information about function "uniquize" and when i run this matlab file ,something wrong like this "Undefined function 'uniquize' for input arguments of type 'int64'.
> Error in construct_dataset_Market (line 50)train_labels = uniquize(train_labels);"
> i want to know, why. thanks twice.
