### ISSUE TITLE
Why should we use function `dist_idx_to_pair_idx` ?

### ISSUE THREAD

**Issue by ZhangYuef** [KovenYu/MAR#14]
Thanks for your sharing.

Why should we have the function `dist_idx_to_pair_idx(d, i)`?  https://github.com/KovenYu/MAR/blob/32051b4d9fd67d7550e04168be780e18b3eecb24/src/utils.py#L606
In fact, I don't understand this function by now. What I know is that this function is to change `dist` index into `pair` index which format is like two tuple `(i), (j)` & `i < j`. But I have no idea about those parameters in it.  Can someone explain this for me or give me some related materials?

Thanks : )

**Comment by KovenYu** [comment]
Thank you @ZhangYuef for your attention.

You are right it simply returns the pairwise index given index in the [pdist-condensed-matrix](https://stackoverflow.com/questions/13079563/how-does-condensed-distance-matrix-work-pdist). The parameter d means the number of given images and i the index.

As for the function body, it is some combinatorial math results. Given the form of pdist-condensed-matrix, you can do the math by hand without much difficulty.
