### ISSUE TITLE
question about batchsize

### ISSUE THREAD

**Issue by xmengxin** [KovenYu/MAR#15]
In main.py line 13,  I'm confused about args.batch_size//2, why devide by 2？ The batchsize is set to    368， actually is 184 when it is devided by 2. Whether we can set batchsize=184 immediately.

**Comment by KovenYu** [comment]
@9meng9 target images and source (auxiliary) images are both needed during training. so we simply use a 5/5 division for them. args.batchsize specifies the overall batch size to fit into gpu memory.
