### ISSUE TITLE
MSMT DATASET

### ISSUE THREAD

**Issue by xmengxin** [KovenYu/MAR#18]
Do you have the oringinal MSMT17dataset, not the .mat? I found that MSMT17 could not be downloaded in "http://www.pkuvmc.com/publications/msmt17.html". Could you share your original  dataset in BaiduYun?

**Comment by KovenYu** [comment]
@9meng9 I believe Longhui (the author of MSMT17) would be happy to do that. Please consider contacting him directly at longhuiwei@pku.edu.cn
