### ISSUE TITLE
Question about MDL loss in paper

### ISSUE THREAD

**Issue by lambert1995** [KovenYu/MAR#23]
Hi, Thanks for your sharing. I have a question about your paper.

The **equation (4)** in 3.2. part
![123](https://user-images.githubusercontent.com/26895870/64764328-6477b480-d574-11e9-915a-7bf997703234.png)

In _P-bar_, you calculate 2-norm of _f(zi) - f(zj)_.
According to content in 3.1. part, index pair _(i, j)_ is found in the unlabeled target dataset _X_; intuitively, we should use image pair _(xi, xj)_ to calculate 2-norm of _f(xi) - f(xj)_.

So I wonder why you use _(zi, zj)_, which is from an auxiliary RE-ID dataset _Z_, to calculate 2-norm in **equation (4)**. Could you explain this?
The same circumstances also happen in _N-bar_.

Thanks a lot !

**Comment by KovenYu** [comment]
Hi @lambert1995 , thanks for your attention! yes that's a subtle typo that we were not able to correct in the paper. your understanding is correct. it should be x instead of z.
