### ISSUE TITLE
MSMT17.mat can't read

### ISSUE THREAD

**Issue by QingzeYin** [KovenYu/MAR#25]
I use python command to run this code. But 'Input/output error' was shown immediately, which said:

OSError: **Can't read data** (file read failed: time = Thu Oct  3 13:19:29 2019
, **filename = 'data/MSMT17.mat'**, file descriptor = 6, errno = 5, error message = 'Input/output error', buf = 0x5629561acaa0, total read size = 3656, bytes this sub-read = 3656, bytes actually read = 18446744073709551615, offset = 6684483979)

Is there some problem with data MSMT17.mat? Cause I re-download this and tried for three times but also obtain same error annotation. 

Could you please give me some suggestions or clues to solve that? Truly thanks!

**Comment by KovenYu** [comment]
Sorry currently I'm away from our lab and for a widely known reason I cannot use VPN to access our server. So for this specific problem I can barely help (it is weird, though, as other people have not observed similar problems). I would suggest you might download the original image dataset and format it by [/data/construct_dataset_MSMT17.m](https://github.com/KovenYu/MAR/blob/master/data/construct_dataset_MSMT17.m).

**Comment by QingzeYin** [comment]
> Sorry currently I'm away from our lab and for a widely known reason I cannot use VPN to access our server. So for this specific problem I can barely help (it is weird, though, as other people have not observed similar problems). I would suggest you might download the original image dataset and format it by [/data/construct_dataset_MSMT17.m](https://github.com/KovenYu/MAR/blob/master/data/construct_dataset_MSMT17.m).

Thanks for replying!
 
Do you think is the problem with _/data/construct_dataset_MSMT17.m_? Or with _MSMT17.mat_? 
Do I need to download original MSMT17 dataset to do pre-train again? Actually I am confused about whether can use your pre-trained model to reproduce.
