### ISSUE TITLE
Could you please share me the MSMT17 original dateset? the official dateset url is missed. Thanks!

### ISSUE THREAD

**Issue by zhicai-liu** [KovenYu/MAR#31]

**Comment by KovenYu** [comment]
Please consider using this: https://pan.baidu.com/s/1O0s_dJcbkku6T0MwlLQecw#list/path=%2F
The images are resized to 384-by-128. You can simply restore these images from the .mat file.

**Comment by KovenYu** [comment]
An alternative link for MSMT17:
https://mega.nz/#!vANGUKBC!uz0fx1DiijEEwblAmMr-h3KYuFR32FaAcggsMPrU8ck
