### ISSUE TITLE
Can not access Baidu Pan

### ISSUE THREAD

**Issue by pribadihcr** [KovenYu/MAR#8]
Hi @KovenYu,

Could you give me an alternative pretrained download storage location?. Thanks

**Comment by KovenYu** [comment]
@pribadihcr okay I'm uploading it to google driver. should finish shortly.

**Comment by KovenYu** [comment]
Hi @pribadihcr  please find the pretrained weight in [GoogleDrive](https://drive.google.com/file/d/1kkktMdezg6oyUuhrXRKuQb6lFqPROj8-/view?usp=sharing). But for the preprocessed dataset files I need one or two more days due to large size.

**Comment by pribadihcr** [comment]
Hi @KovenYu Thank you very much. I will try the pretrained model first.
