### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by haofeng0928** [KovenYu/MAR#9]
i dont have 40G cpu memory, is there another solution?

**Comment by KovenYu** [comment]
@haofeng0928 
In my implementation I load the entire dataset into RAM for higher speed, but it costs more cpu momery, especially for the MSMT17. To reduce the cpu memory usage you can change the data loading style.

Specifically, you need to use the [ImageFolder](https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder) Dataset Constructor for the MSMT17 dataset. Please modify [L521 in utils.py](https://github.com/KovenYu/MAR/blob/master/src/utils.py#L521) to use the ImageFolder. Note that source_data is a Dataset object. Once you get this done, the memory usage would be drastically reduced to about only 5GB or less.
